### ISSUE TITLE
I have no idea how it happened

### ISSUE THREAD

**Issue by ZwerOxotnik** [TGNThump/factorio-publish-mod-action#6]
https://github.com/ZwerOxotnik/factorio-candran-example/runs/4922941711?check_suite_focus=true
```
Run TGNThump/factorio-publish-mod-action@v1
  with:
    mod_portal_username: ***
    mod_portal_password: ***
    mod_name: candran-example
    asset_path: ./candran-example_0.1.0.zip
    asset_name: candran-example_0.1.0.zip
  env:
    LUA_PATH: ;;/home/runner/.luarocks/share/lua/5.4/?.lua;/home/runner/.luarocks/share/lua/5.4/?/init.lua;/home/runner/work/factorio-candran-example/factorio-candran-example/.luarocks/share/lua/5.4/?.lua;/home/runner/work/factorio-candran-example/factorio-candran-example/.luarocks/share/lua/5.4/?/init.lua
    LUA_CPATH: ;;/home/runner/.luarocks/lib/lua/5.4/?.so;/home/runner/work/factorio-candran-example/factorio-candran-example/.luarocks/lib/lua/5.4/?.so
Logging in to Factorio Mod Portal as '***'
```
```
Error: Failed to post update to Mod Portal: TypeError: Cannot read property '1' of null
```
